# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: package install ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-package:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9"]
        os: [ubuntu-latest]
        extra: ["", "[ocr]"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and package
      run: |
        python -m pip install --upgrade pip setuptools
        # python -m pip install flake8 pytest
        python -m pip install -e .${{ matrix.extra }} --no-use-pep517
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run usage.py
      run: |
          python usage.py
  
  install-package-3_10:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies and package
      run: |
        python -m pip install --upgrade pip setuptools
        sudo apt-get install -y python3-setuptools
        # python -m pip install flake8 pytest
        python -m pip install -e . --no-use-pep517
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run usage.py
      run: |
          python usage.py

